spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: body
    url: jdbc:mariadb://localhost:3305/body
    password: body
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  mail:
    host: smtp.gmail.com
    port: 587
    username: 1090jun@gmail.com
    password: ortsuybhqlpnpgka
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      springframework: info
    net:
      ict: debug
server:
  port: '8081'
